version: "3.9"
services:
  report_payment-service:
    build: 
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 6051:6051
    networks:
      - microservices

networks:
  microservices:
    name: microservices
